swagger: "2.0"
info:
  version: "1.0"
  title: "MNIST"
tags:
  - name: "MNIST-Controller"

paths:
  /mnist:
    post:
      tags:
        - "MNIST-Controller"
      summary: "getMNISTProbability"
      operationId: "getMNISTProbability"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "requestBody"
        description: "requestBody"
        required: true
        schema:
          $ref: "#/definitions/MNISTImageRequestBody"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/MNISTProbabilityResponse"

definitions:
  MNISTImageRequestBody:
    type: "object"
    properties:
      imageBase64:
        type: "string"
    required:
      - imageBase64
  MNISTProbabilityResponse:
    type: "object"
    properties:
      probability_list:
        type: "array"
        items:
          type: "number"
          format: "float"
    required:
      -  probability_list