AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 50
    MemorySize: 1024
  Api:
    BinaryMediaTypes:
      - image/png
      - image/jpg
      - image/jpeg

Resources:
  MNISTFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Inference:
          Type: Api
          Properties:
            Path: /mnist
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src/mnist
      DockerTag: python3.9-v1

Outputs:
  InferenceApi:
    Description: "API Gateway endpoint URL for Prod stage for Inference function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mnist/"
  MNISTFunction:
    Description: "Inference Lambda Function ARN"
    Value: !GetAtt MNISTFunction.Arn
  MNISTFunctionIamRole:
    Description: "Implicit IAM Role created for Inference function"
    Value: !GetAtt MNISTFunctionRole.Arn
